# Templatized Service manifest
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

# Example of a Service manifest
# apiVersion: v1
# kind: Service
# metadata:
#   name: release-name-service
# spec:
#   selector:
#     app.kubernetes.io/instance: release-name
#   type: ClusterIP
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 9000